-- 曝光表：
CREATE TABLE `ocpx_v1_imp` (
  `req_time` datetime NULL,
  `uid` int NULL,
  `support_id` int NULL,
  `agent_id` int NULL,
  `product_id` int NULL,
  `channel_id` int NULL,
  `product_channel` varchar(128) NULL,
  `place_id` varchar(128) NULL,
  `dhh_task_id` varchar(128) NULL,
  `unikey` varchar(16) NULL,
  `advertiser_id` varchar(128) NULL,
  `campaign_id` varchar(128) NULL,
  `ad_id` varchar(128) NULL,
  `cid` varchar(128) NULL,
  `user_id` varchar(20) NULL,
  `test_status` int NULL,
  `os` varchar(32) NULL,
  `ua` text NULL,
  `ua_md5` varchar(128) NULL,
  `ip` varchar(64) NULL,
  `type` varchar(32) NULL,
  `is_loss` int NULL,
  `err` text NULL COMMENT "error info",
  `idfa_sum` varchar(128) NULL,
  `oaid_sum` varchar(128) NULL,
  `callback_param` varchar(10240) NULL,
  `imei` varchar(128) NULL,
  `idfa` varchar(128) NULL,
  `oaid` varchar(512) NULL,
  `imei_sum` varchar(128) NULL,
  `log_time` bigint NULL DEFAULT "0",
  `caid` varchar(256) NULL DEFAULT "" COMMENT "caid version_md5",
  `req_id` varchar(256) NULL DEFAULT "",
  `caidjson` text NULL DEFAULT "",
  `servername` varchar(128) NOT NULL DEFAULT "" COMMENT "服务名称hostname:port"
) DUPLICATE KEY(`req_time`, `uid`, `support_id`, `agent_id`, `product_id`, `channel_id`, `product_channel`, `place_id`, `dhh_task_id`);

-- 点击表：
CREATE TABLE `ocpx_v1_clk` (
  `req_time` datetime NULL,
  `uid` int NULL,
  `support_id` int NULL,
  `agent_id` int NULL,
  `product_id` int NULL,
  `channel_id` int NULL,
  `product_channel` varchar(128) NULL,
  `place_id` varchar(65533) NULL,
  `dhh_task_id` varchar(65533) NULL,
  `unikey` varchar(65533) NULL,
  `advertiser_id` varchar(65533) NULL,
  `campaign_id` varchar(65533) NULL,
  `ad_id` varchar(65533) NULL,
  `cid` varchar(128) NULL,
  `user_id` varchar(20) NULL,
  `test_status` int NULL,
  `os` varchar(32) NULL,
  `ua_md5` varchar(128) NULL,
  `ip` varchar(64) NULL,
  `idfa_sum` varchar(128) NULL,
  `oaid_sum` varchar(128) NULL,
  `callback_param` varchar(10240) NULL,
  `imei` varchar(128) NULL,
  `idfa` varchar(128) NULL,
  `oaid` varchar(512) NULL,
  `imei_sum` varchar(128) NULL,
  `log_time` bigint NULL DEFAULT "0",
  `type` varchar(65533) NULL,
  `is_loss` int NULL,
  `err` text NULL COMMENT "error info",
  `caid` varchar(256) NULL DEFAULT "" COMMENT "caid version_md5",
  `req_id` varchar(128) NULL DEFAULT "",
  `caidjson` text NULL DEFAULT "",
  `servername` varchar(128) NOT NULL DEFAULT "" COMMENT "服务名称hostname:port"
) DUPLICATE KEY(`req_time`, `uid`, `support_id`, `agent_id`, `product_id`, `channel_id`, `product_channel`, `place_id`, `dhh_task_id`);

-- 转化表：
CREATE TABLE `ocpx_v1_track` (
  `req_time` datetime NULL,
  `uid` int NULL,
  `support_id` int NULL,
  `agent_id` int NULL,
  `product_id` int NULL,
  `channel_id` int NULL,
  `product_channel` varchar(128) NULL,
  `place_id` varchar(128) NULL,
  `dhh_task_id` varchar(128) NULL,
  `unikey` varchar(16) NULL,
  `advertiser_id` varchar(128) NULL,
  `campaign_id` varchar(128) NULL,
  `ad_id` varchar(128) NULL,
  `cid` varchar(128) NULL,
  `event_name` varchar(128) NULL,
  `up_event_name` varchar(128) NULL,
  `down_event_name` varchar(128) NULL,
  `action_pv` tinyint NULL,
  `depth_action_pv` tinyint NULL,
  `cb_action_pv` tinyint NULL,
  `cb_depth_action_pv` tinyint NULL,
  `user_id` varchar(20) NULL,
  `test_status` int NULL,
  `ip` varchar(64) NULL,
  `type` varchar(32) NULL,
  `is_loss` int NULL,
  `err` text NULL COMMENT "error info",
  `idfa_sum` varchar(128) NULL,
  `oaid_sum` varchar(128) NULL,
  `callback_param` varchar(10240) NULL,
  `ua_md5` varchar(128) NULL,
  `imei` varchar(128) NULL,
  `idfa` varchar(128) NULL,
  `oaid` varchar(512) NULL,
  `imei_sum` varchar(128) NULL,
  `log_time` bigint NULL DEFAULT "0",
  `ts` int NULL DEFAULT "0",
  `caid` varchar(256) NULL DEFAULT "" COMMENT "caid version_md5",
  `req_id` varchar(128) NULL DEFAULT "",
  `caidjson` text NULL DEFAULT "",
  `servername` varchar(128) NOT NULL DEFAULT "" COMMENT "服务名称hostname:port"
) DUPLICATE KEY(`req_time`, `uid`, `support_id`, `agent_id`, `product_id`, `channel_id`, `product_channel`, `place_id`, `dhh_task_id`);

-- 京东曝光表:
CREATE TABLE `ocpx_jd_imp` (
  `req_time` datetime NULL,
  `uid` int NULL,
  `product_channel` varchar(128) NULL,
  `p1` varchar(32) NULL,
  `cid` varchar(128) NULL,
  `advertiser_id` varchar(128) NULL,
  `support_id` int NULL,
  `agent_id` int NULL,
  `product_id` int NULL,
  `channel_id` int NULL,
  `place_id` varchar(128) NULL,
  `dhh_task_id` varchar(128) NULL,
  `unikey` varchar(16) NULL,
  `campaign_id` varchar(128) NULL,
  `ad_id` varchar(128) NULL,
  `event_name` varchar(128) NULL,
  `up_event_name` varchar(128) NULL,
  `down_event_name` varchar(128) NULL,
  `action_pv` tinyint NULL,
  `depth_action_pv` tinyint NULL,
  `cb_action_pv` tinyint NULL,
  `cb_depth_action_pv` tinyint NULL,
  `user_id` varchar(20) NULL,
  `test_status` int NULL,
  `ip` varchar(64) NULL,
  `type` varchar(32) NULL,
  `is_loss` int NULL,
  `err` text NULL COMMENT "error info",
  `idfa_sum` varchar(128) NULL,
  `oaid_sum` varchar(128) NULL,
  `callback_param` varchar(10240) NULL,
  `ua_md5` varchar(128) NULL,
  `imei` varchar(128) NULL,
  `idfa` varchar(128) NULL,
  `oaid` varchar(512) NULL,
  `imei_sum` varchar(128) NULL,
  `log_time` bigint NULL DEFAULT "0",
  `ts` int NULL DEFAULT "0",
  `caid` varchar(256) NULL DEFAULT "" COMMENT "caid version_md5",
  `req_id` varchar(128) NULL DEFAULT "",
  `caidjson` text NULL DEFAULT "",
  `servername` varchar(128) NOT NULL DEFAULT "" COMMENT "服务名称hostname:port"
) DUPLICATE KEY(`req_time`, `uid`, `product_channel`, `p1`, `cid`, `advertiser_id`);

-- 京东点击表：
CREATE TABLE `ocpx_jd_clk` (
  `req_time` datetime NULL,
  `uid` int NULL,
  `product_channel` varchar(128) NULL,
  `p1` varchar(32) NULL,
  `cid` varchar(128) NULL,
  `advertiser_id` varchar(128) NULL,
  `support_id` int NULL,
  `agent_id` int NULL,
  `product_id` int NULL,
  `channel_id` int NULL,
  `place_id` varchar(128) NULL,
  `dhh_task_id` varchar(128) NULL,
  `unikey` varchar(16) NULL,
  `campaign_id` varchar(128) NULL,
  `ad_id` varchar(128) NULL,
  `event_name` varchar(128) NULL,
  `up_event_name` varchar(128) NULL,
  `down_event_name` varchar(128) NULL,
  `action_pv` tinyint NULL,
  `depth_action_pv` tinyint NULL,
  `cb_action_pv` tinyint NULL,
  `cb_depth_action_pv` tinyint NULL,
  `user_id` varchar(20) NULL,
  `test_status` int NULL,
  `ip` varchar(64) NULL,
  `type` varchar(32) NULL,
  `is_loss` int NULL,
  `err` text NULL COMMENT "error info",
  `idfa_sum` varchar(128) NULL,
  `oaid_sum` varchar(128) NULL,
  `callback_param` varchar(10240) NULL,
  `ua_md5` varchar(128) NULL,
  `imei` varchar(128) NULL,
  `idfa` varchar(128) NULL,
  `oaid` varchar(512) NULL,
  `imei_sum` varchar(128) NULL,
  `log_time` bigint NULL DEFAULT "0",
  `ts` int NULL DEFAULT "0",
  `caid` varchar(256) NULL DEFAULT "" COMMENT "caid version_md5",
  `req_id` varchar(128) NULL DEFAULT "",
  `caidjson` text NULL DEFAULT "",
  `servername` varchar(128) NOT NULL DEFAULT "" COMMENT "服务名称hostname:port"
) DUPLICATE KEY(`req_time`, `uid`, `product_channel`, `p1`, `cid`, `advertiser_id`);

-- 京东转化表：
CREATE TABLE `ocpx_jd_callback` (
  `req_time` datetime NULL,
  `uid` int NULL,
  `product_channel` varchar(128) NULL,
  `p1` varchar(16) NULL,
  `cid` varchar(128) NULL,
  `advertiser_id` varchar(128) NULL,
  `up_event_name` varchar(128) NULL,
  `err` text NULL COMMENT "error info",
  `support_id` int NULL,
  `agent_id` int NULL,
  `product_id` int NULL,
  `channel_id` int NULL,
  `place_id` varchar(128) NULL,
  `dhh_task_id` varchar(128) NULL,
  `unikey` varchar(16) NULL,
  `campaign_id` varchar(128) NULL,
  `ad_id` varchar(128) NULL,
  `event_name` varchar(128) NULL,
  `down_event_name` varchar(128) NULL,
  `action_pv` tinyint NULL,
  `depth_action_pv` tinyint NULL,
  `cb_action_pv` tinyint NULL,
  `cb_depth_action_pv` tinyint NULL,
  `user_id` varchar(20) NULL,
  `test_status` int NULL,
  `ip` varchar(64) NULL,
  `type` varchar(32) NULL,
  `is_loss` int NULL,
  `idfa_sum` varchar(128) NULL,
  `oaid_sum` varchar(128) NULL,
  `callback_param` varchar(10240) NULL,
  `ua_md5` varchar(128) NULL,
  `imei` varchar(128) NULL,
  `idfa` varchar(128) NULL,
  `oaid` varchar(512) NULL,
  `imei_sum` varchar(128) NULL,
  `log_time` bigint NULL DEFAULT "0",
  `ts` int NULL DEFAULT "0",
  `caid` varchar(1000) NULL DEFAULT "" COMMENT "caid version_md5",
  `req_id` varchar(128) NULL DEFAULT "",
  `caidjson` text NULL DEFAULT "",
  `servername` varchar(128) NOT NULL DEFAULT "" COMMENT "服务名称hostname:port"
) DUPLICATE KEY(`req_time`, `uid`, `product_channel`, `p1`, `cid`, `advertiser_id`, `up_event_name`);
